### ISSUE TITLE
Contents.create/update/remove shouldn't require usage of raw JSON

### ISSUE THREAD

**Issue by cvrebert** [jcabi/jcabi-github#1097]
`Contents.create()`, `Contents.update()`, and `Contents.remove()` each currently accept a raw JsonObject as one of their arguments. This is annoying to work with and not very typesafe. It would be better if these methods accepted structured, well-typed objects instead.

**Comment by dmarkov** [comment]
@yegor256 please pay attention to this issue

**Comment by amihaiemil** [comment]
@cvrebert I took over as architect these days and cleaning some Issues now. 

Unfortunately, I do not agree with this Issue. Whenever possible, I would let the user supply a JsonObject or in general the raw payload. The reason is simple:

1. Users have to learn the API (at least the endpoints they are using) anyway, to know how to build the input properly (e.g. even if we supply model objects, they still have to know what attributes to pass, in what combination etc)

2. If we burdain the library with models then we have to struggle to always respect Github API's. 

I think it's simply more flexible to just expect the raw payload and pass it over to Github.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
