### ISSUE TITLE
Cannot return mock response with MkGitHub.entry

### ISSUE THREAD

**Issue by collinpeters** [jcabi/jcabi-github#1414]
Since `MkGitHub` is a final class it cannot be extended and since the `entry` method returns an immutable `FakeRequest` it can't be changed. I don't see any recourse here, how are you supposed to mock `entry()`?

For the record, I need `entry()` in order to use the endpoints for Apps. See here: https://developer.github.com/apps/building-github-apps/authenticating-with-github-apps/#authenticating-as-an-installation

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
@collinpeters[/z](https://www.0crat.com/u/collinpeters) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C9R53K5JA) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by amihaiemil** [comment]
@collinpeters The ``Mk*`` classes are basically an out-of-the-box mock of the Github API, you do not mock those classes. They are final because they are not supposed to be extended (we believe that implementation inheritance is a bad practice in OOP). 

If you need them to have some other behaviour, you can always decorate them (all the classes are implementing interfaces). Or, if you can't change their behaviour, you can always create your own mocks, by mocking the interfaces. 

In this case, it sounds like you need to do something like this:

```java
final Github apps = Mockito.mock(Github.class);
Mockito.when(apps.entry()).thenReturn(new ApacheRequest(...)); //or new JdkRequest
```

Does this help? Feel free to ask if you need more details :D

**Comment by collinpeters** [comment]
Understood @amihaiemil. Was hoping there was a `MkEntry` which would allow for mocking of the json returned by the `FakeRequest` currently returned by `MkGitHub.entry()`.

Something like 
```
mkGitHub.entry().route("/installation/1/...", json1).route("/installation/2/...", json2)
```

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
