### ISSUE TITLE
Remove grizzly and put takes instead

### ISSUE THREAD

**Issue by fabriciofx** [jcabi/jcabi-github#1481]
Let's remove grizzly e put takes (takes.org) instead.

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
@fabriciofx[/z](https://www.0crat.com/u/fabriciofx) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C9R53K5JA) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by amihaiemil** [comment]
@fabriciofx grizzly is used in the tests, and it is there for jcabi-http's MkContainer, right?

I don't see any advantage in using takes, only a big effort of rewriting all unit tests...

**Comment by fabriciofx** [comment]
@amihaiemil The problem is `grizzly` dependency is too much outdated and the new versions change the API. So, IMHO if we will change a lot the API is better change grizzly to takes.

**Comment by amihaiemil** [comment]
@fabriciofx Even so, ``grizzly`` is only used in the tests and it is not directly used by ``jcabi-github`` (if I remember well) - it is used internally by ``jcabi-http``... so if there are any changes in the API of grizzly, they should be fixed in jcabi-http.

But anyway, it is a big effort which is not worth it, considering it's all about the unit tests. :) 
I also wouldn't be confortable reimplementing all the tests...

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-github#1481` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
