### ISSUE TITLE
Create Repo in Organization

### ISSUE THREAD

**Issue by ShalomGottesman** [jcabi/jcabi-github#1501]
Is there a way to create a repository inside an organization?

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
@shalomgottesman[/z](https://www.0crat.com/u/shalomgottesman) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C9R53K5JA) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by amihaiemil** [comment]
@ShalomGottesman I'm not sure. I searched the API Docs and found nothing in this matter. 

You can create a repo under the authenticated user like this: 

```java
final Github gh = new RtGithub(...);
final Repo created = gh.repos().create(...);
```

After creating it, an option would be to [transfer](https://developer.github.com/v3/repos/#transfer-a-repository) it (Github API allows it). 

However, ``jcabi-github`` doesn't have the ``Repo.transfer(...)`` method. Maybe you can implement it? It's not hard at all. Just look inside [RtRepo](https://github.com/jcabi/jcabi-github/blob/master/src/main/java/com/jcabi/github/RtRepo.java), how other methods are implemented.

**Comment by amihaiemil** [comment]
@ShalomGottesman You can also make the ``transfer`` request yourself. The ``Github`` object offers the [entry()](https://github.com/jcabi/jcabi-github/blob/master/src/main/java/com/jcabi/github/RtGithub.java#L153) method which returns the underlying HTTP Request. 

Look inside [RtGithub](https://github.com/jcabi/jcabi-github/blob/master/src/main/java/com/jcabi/github/RtGithub.java) to see how the ``Request`` is configured and what paths you need to add to it in order to have the right URI.

**Comment by amihaiemil** [comment]
fixed. Continuing work in #1503 for release.

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-github#1501` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
