### ISSUE TITLE
Content doesn't support JsonArray reading

### ISSUE THREAD

**Issue by darkled** [jcabi/jcabi-github#968]
There is the method `com.jcabi.github.Content.json()` which returns `JsonObject`. But in some cases (e.g. #903 which is about getting invoking `com.jcabi.github.RtContents.content(String, String)` on directories) we can need to process `JsonArray`'s instead. If there is no way to do that for the moment, it should be introduced.

**Comment by dmarkov** [comment]
I'll ask someone to take care of this task soon

**Comment by dmarkov** [comment]
@aoxa can you please help? Keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If you have any technical questions, don't hesitate to ask right here... Task's budget is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by dmarkov** [comment]
@darkled thanks a lot for reporting, **15 mins** added to your acc, pmt ID `50045055`

**Comment by aoxa** [comment]
Is there a use case that I can execute to replay the defect? Please bear in mind I'm new to the project and will need some time to get up to speed.
Cheers!

**Comment by darkled** [comment]
@aoxa you can try this snippet:
```java
final Repos repos = github().repos();
final Repo repo =  repos.get(new Coordinates.Simple("jcabi/jcabi-github"));
System.out.println(new Content.Smart(repo.contents().get("src/main/java/com/jcabi/github/Users.java")).url());
// #output https://api.github.com/repos/jcabi/jcabi-github/contents/src/main/java/com/jcabi/github/Users.java?ref=master
System.out.println(new Content.Smart(repo.contents().get("src/main/java/com/jcabi/github/mock")).url());
```

**Comment by aoxa** [comment]
Well, I see the issue. The problem though is not a defect per se. If you ran the get, you are trying to access an object, simple content of an url, since you get a directory, you get a list of objects. So the correct approach would've been to call iterate instead, that is present in content and is intended to return an iterable collection of elements.
So, one possble solution is to create an exception that translates the JSonArray exception into an packege exception that will make it more user friendly, stating the preceding behavior.
Another solution, well, I'd love to know what you'd expect from that call.
Cheers

**Comment by aoxa** [comment]
sorry about the delay in the response but I was unable to get to a pc for 4 days.

**Comment by darkled** [comment]
@aoxa Saying *Content doesn't support JsonArray reading* I meant that it should read it (e.g. as a collection of `JsonObject`'s) without throwing any exception.

**Comment by dmarkov** [comment]
@aoxa you're holding this ticket for 15 days already. If it's not finished (and closed) in the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle ([this article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck)... -30 added to your rating, at the moment it is: -60

**Comment by dmarkov** [comment]
@aoxa you've been working with this task for too long. I'm sorry, but I'll assign someone else. Please stop working with it. See our [no obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle... -60 to your rating, your total score is -270

**Comment by dmarkov** [comment]
@apocarteres please proceed, it's yours

**Comment by dmarkov** [comment]
@marcuss please proceed, it's yours

**Comment by marcuss** [comment]
@dmarkov please assign this to someone else

**Comment by dmarkov** [comment]
> @dmarkov please assign this to someone else

@marcuss deducted 30 from your rating :(

**Comment by dmarkov** [comment]
> @dmarkov please assign this to someone else

@marcuss I will try to find someone else

**Comment by dmarkov** [comment]
@shelan this task is for you, keep [these principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions... The budget of this task is **30 mins**. This is exactly how much time will be compensated, when the task is completed. Read about our [Definition of Done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by shelan** [comment]
@dmarkov I did a study of the problem including the referenced #903. IMHO the real cause of the problem is the way Contents API is being used. According to the snippet following gives the exception.

`repo.contents().get("src/main/java/com/jcabi/github/mock")`

But it gives array of content not a single content.  Following is an example of one file being retrieved.

`repo.contents().get("src/main/java/com/jcabi/github/Users.java")`

If you are retrieving a directory you should use following API.
repo.contents().iterate(url,ref). 

I think API designer has designed the API in such a way. Because in the method doc it says following.
for the contents().get ( Please fine **a file**)

/**
     * Get the contents of **a file** or symbolic link in a repository.
     * @param path The content path
     * @param ref The name of the commit/branch/tag.
     * @return Content fetched

Therefore i believe this should not be refactored and current API seems to be okay.

If we change the API to match 100% what github API does (It returns both one file and list of files) we should introduce a method which returns an Iterator<Content> by default and deprecate existing method.

**Comment by shelan** [comment]
@darkled @dmarkov according to my previous comment , I believe we can use the API using iterate() method for folders or submodules rather using get(). Please suggest if you have any other concerns.

**Comment by darkled** [comment]
@shelan agreed, let's add information that the method `get()` is not allowed to be used for folders and we need to `iterate()` instead.

**Comment by shelan** [comment]
Thanks @darkled. I have created a PR here. #1173 . But it looks like CI build is failing for following reason as per the build log.
`
{"message":"API rate limit exceeded for 52.0.240.122. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://developer.github.com/v3/#rate-limiting"}>`

**Comment by dmarkov** [comment]
> @dmarkov @darkled I did a study of the problem including the referenced #903. IMHO the real cause of the problem is the way Contents API is being used. According to the snippet following gives the exception.
> 
> `repo.contents().get("src/main/java/com/jcabi/github/mock")`
> 
> But it gives array of content not a single content.  Following is an example of one file being retrieved.
> 
> `repo.contents().get("src/main/java/com/jcabi/github/Users.java")`
> 
> If you are retrieving a directory you should use following API.
> repo.contents().iterate(url,ref). 
> 
> I think API designer has designed the API in such a way. Because in the method doc it says following.
> for the contents().get ( Please find phrase **a file**)
> 
> /**
>      * Get the contents of **a file** or symbolic link in a repository.
>      * @param path The content path
>      * @param ref The name of the commit/branch/tag.
>      * @return Content fetched
> 
> Therefore i believe this should not be refactored and current API seems to be okay.
> 
> If we change the API to match 100% what github API does (It returns both one file and list of files) we should introduce a method which returns an Iterator<Content> by default and deprecate existing method.
> 

@shelan please, don't do technical discussions in tickets (moreover, I can't help you, I'm a project manager, not a developer). every time you see something unclear, submit new tickets. see http://www.yegor256.com/2015/01/15/how-to-cut-corners.html

**Comment by dmarkov** [comment]
@shelan check this ["no obligations principle"](http://www.xdsd.org/2014/04/13/no-obligations-principle.html).. This task is on your name for at least 15 days. If you can't close it within the next 48 hours I will have to assign someone else to it. [This article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck... -30 added to your rating, current score is: [+15](http://www.netbout.com/b/35659?open=rating)

**Comment by shelan** [comment]
@dmarkov issue is not closed because PR #1173 is not closed because of CI issues. I have reported it well with in the time frame. I have reported all the issues #1175.

Is there a way that i can do to close the issue? I feel it is unfair to reduce my rating when i have done everything as described in the process. Please clarify if i have misunderstood.

**Comment by darkled** [comment]
@shelan in such cases you need to report impediment in the way described in [policy](http://www.teamed.io/policy.html#11)

**Comment by darkled** [comment]
@dmarkov we are waiting for #1175

**Comment by shelan** [comment]
@darkled Thank you very much for the information.

**Comment by dmarkov** [comment]
> @dmarkov we are waiting for #1175 

@darkled sure, let's wait for #1175

**Comment by shelan** [comment]
@darkled PR #1173 is closed. Could you please close the issue?

**Comment by darkled** [comment]
thanks, closing

**Comment by dmarkov** [comment]
@shelan thanks, I just added **30 mins** to your account, payment `67512000`, 434 hours and 6 mins spent. +30 added to your rating, current score is: [+60](http://www.netbout.com/b/35659?open=rating)
