### ISSUE TITLE
Test RtRepoITCase.iteratesLanguages fails during merge

### ISSUE THREAD

**Issue by dpisarenko** [jcabi/jcabi-github#999]
When trying to merge https://github.com/jcabi/jcabi-github/pull/985 , following error occured:

```
Failed tests: RtRepoITCase.iteratesLanguages:163 
Expected: not an empty iterable but: was <[]>  Tests run: 111, Failures: 1, Errors: 0, Skipped: 3
```

Full log is here: http://www.rultor.com/t/1712-71175391

The error didn't occure before merge.

I didn't touch the `RtRepoITCase` test.

Please make sure that this test passes during merge.

**Comment by yegor256** [comment]
@dpisarenko how can I reproduce this (in master)?

**Comment by dpisarenko** [comment]
@yegor256 I don't know. This test failed only during merge, not in the Travis build.

**Comment by dpisarenko** [comment]
@yegor256 Theoretically, you could try to merge the master branch (or something else, which will make rultor run the integration tests).

**Comment by yegor256** [comment]
@dpisarenko if something is wrong in your branch, it's your problem inside the branch. we can't call it a bug and fix. since nobody has access to your branch (and it's inside your scope). so, either close this ticket or change its description so that it sounds more like "master branch is broken, but I don't know exactly why and where"

**Comment by dpisarenko** [comment]
@yegor256 I can close the issue. But can you please try to merge the PR https://github.com/jcabi/jcabi-github/pull/985 again?
